name: Duplicate Issue on Comment

on:
  issue_comment:
    types: [created]

jobs:
  duplicate-issue:
    if: ${{ github.event.comment.body == 'duplicate' }}
    runs-on: ubuntu-latest
    steps:
      - name: Duplicate the issue
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d "{\"title\":\"${ISSUE_TITLE} (Duplicate)\",\"body\":\"${ISSUE_BODY}\"}"
